-- SQLite

--consulta capaz de exibir todos os funcionários e seus respectivos cargos
SELECT EMPLOYEES.NAME AS 'NOME',
       EMPLOYEES.PHONE_NUMBER AS 'CONTATO',
       EMPLOYEES.CONTRACT_DATE AS 'INICIO DO CONTRATO',
       POSITIONS.DESCRIPTION AS 'CARGO'
       FROM EMPLOYEES

       INNER JOIN POSITIONS ON (EMPLOYEES.POSITION_ID = POSITIONS.ID);