-- SQLite
--  consulta capaz de exibir somente os funcionários que realizaram mais ou igual a 2 locações.

SELECT EMPLOYEES.NAME AS 'VENDEDORES COM 2 OU MAIS LOCAÇÕES',
  COUNT(LOCATIONS.EMPLOYEE_ID) AS 'NUMERO DE LOCAÇÕES'
  FROM LOCATIONS
  INNER JOIN EMPLOYEES ON (LOCATIONS.EMPLOYEE_ID = EMPLOYEES.ID)
  GROUP BY LOCATIONS.EMPLOYEE_ID
  HAVING COUNT(LOCATIONS.EMPLOYEE_ID >= 2);