-- SQLite
--consulta capaz de exibir somente os clientes que realizaram mais ou igual a 2 locações.


SELECT CUSTOMERS.ID AS 'CODIGO',
  CUSTOMERS.NAME AS 'CLINTES COM 2 OU MAIS LOCAÇÕES',
  COUNT(LOCATIONS.CUSTOMER_ID) AS 'NUMERO DE LOCAÇÕES'
  FROM LOCATIONS
  INNER JOIN CUSTOMERS ON (LOCATIONS.CUSTOMER_ID = CUSTOMERS.ID)
  GROUP BY LOCATIONS.CUSTOMER_ID
  HAVING COUNT(LOCATIONS.CUSTOMER_ID) >= 2;
