-- SQLite
-- consulta capaz de exibir todas as locações realizadas, assim como também o nome do cliente, do automóvel e do
--funcionário vinculados em cada locação

SELECT LOCATIONS.ID AS 'CODIGO',
  CUSTOMERS.NAME AS 'NOME CLIENTE',
  CARS.NAME AS 'CARRO',
  EMPLOYEES.NAME AS 'NOME FUNCIONÁRIO',
  START_DATE AS 'INICIO LOCACAO',
  END_DATE AS 'DATA DEVOLUÇÃO',
  TOTAL AS 'VALOR TOTAL'  
  FROM LOCATIONS

  INNER JOIN CUSTOMERS ON(LOCATIONS.CUSTOMER_ID = CUSTOMERS.ID)
  INNER JOIN CARS ON (LOCATIONS.CAR_ID = CARS.ID)
  INNER JOIN EMPLOYEES ON (LOCATIONS.EMPLOYEE_ID = EMPLOYEES.ID);