-- SQLite
-- consulta capaz de exibir todas as locações realizadas, 
-- entre as datas “2022-05-20” a “2022-12-25”

SELECT LOCATIONS.ID AS 'CODIGO',
  CUSTOMERS.NAME AS 'NOME CLIENTE',
  CARS.NAME AS 'CARRO',
  EMPLOYEES.NAME AS 'NOME FUNCIONÁRIO',
  START_DATE AS 'INICIO LOCACAO',
  END_DATE AS 'DATA DEVOLUÇÃO',
  TOTAL AS 'VALOR TOTAL'  
  FROM LOCATIONS

  INNER JOIN CUSTOMERS ON(LOCATIONS.CUSTOMER_ID = CUSTOMERS.ID)
  INNER JOIN CARS ON (LOCATIONS.CAR_ID = CARS.ID)
  INNER JOIN EMPLOYEES ON (LOCATIONS.EMPLOYEE_ID = EMPLOYEES.ID)
  WHERE START_DATE AND END_DATE BETWEEN '2022-05-20' AND '2022-12-25';
